### ISSUE TITLE
How to get pdf fields?

### ISSUE THREAD

**Issue by mel-cdn** [chinapandaman/PyPDFForm#365]
How to retrieve the pdf field keys? 
Also, is there a way to not flatten the pdf? Make those fields still editable after the fill?

**Comment by chinapandaman** [comment]
Hello,

You can try using the `generate_schema` method, [here](https://github.com/chinapandaman/PyPDFForm/blob/master/docs/examples.md#generate-json-schema) is an example.

As far as not flatten the PDF goes, it was a functionality that was supported long ago but was eventually deprecated because it introduced all sorts of problems during merging multiple non-flattened PDF forms. Now the library always flattens and there's currently no way otherwise.

Thanks.

**Comment by chinapandaman** [comment]
Hello,

Were you able to resolve your problems? If so please close this issue. If there are no more comments in this thread for a week I will close this issue next Friday.

Thanks.
