### ISSUE TITLE
New line (carriage return) in text box

### ISSUE THREAD

**Issue by ebardelli** [chinapandaman/PyPDFForm#414]
I'm trying to fill a form with a multiline comment box. I would like to insert new lines/carriage returns in the textbox. I noticed that the new line (`\n`) codes are interpreted as a black box character in the filled pdf.

I believe that the error comes from the implementation in [this function](https://github.com/chinapandaman/PyPDFForm/blob/deb3fc1bfbd20b0fb2bee7bc72ba712d2605f95d/PyPDFForm/core/template.py#L169-L203).

Would it be possible to add a wrapper around [these lines](https://github.com/chinapandaman/PyPDFForm/blob/deb3fc1bfbd20b0fb2bee7bc72ba712d2605f95d/PyPDFForm/core/template.py#L178-L187) to first split the text using `\n`?

**Comment by chinapandaman** [comment]
I made more changes and it should work now. Here is the generated PDF I used for the test case: https://github.com/chinapandaman/PyPDFForm/blob/PPF-415/pdf_samples/scenario/issues/PPF-415-expected.pdf

The reason my changes didn't work when I initially post you was because of [this part](https://github.com/chinapandaman/PyPDFForm/blob/master/PyPDFForm/core/template.py#L189-L201). What this is doing is to automatically adjust number of words on each line based on the horizontal width of the paragraph field, which completely negates the logic of splitting into different lines via new line symbol as it will try to put words into shorter lines anyway. I made some changes so that the above logic, when detecting new line symbol at the end of each line, will no longer do that.

**Comment by chinapandaman** [comment]
I noticed this right after I posted you so I made more changes as you made your most recent post. Here is a new PDF I generated using your recent template and snippet.
[output.pdf](https://github.com/chinapandaman/PyPDFForm/files/13625559/output.pdf)

The word `tincidunt` still overflows by about a character and this might be an inaccuracy of how I calculate text wrap length and I will need to look into this in the future. But for the most part it should be good.

**Comment by chinapandaman** [comment]
Forget about what I said above, I think I have the overflow issue fixed. I just need some time to fix the logic that calculates the text wrap length.

Here is how it looks now: https://github.com/chinapandaman/PyPDFForm/blob/PPF-415/pdf_samples/scenario/issues/PPF-415-2-expected.pdf

**Comment by chinapandaman** [comment]
Try now? Just put in a fix.
