### ISSUE TITLE
Widget format information ignored? (Underline, bold, etc.)

### ISSUE THREAD

**Issue by mrvisiol** [chinapandaman/PyPDFForm#460]
Thank you for this pdf library. It is the easiest one I have found.

I noticed the fill method creates new text objects with default font and formats, and removes the widgets from the form. 

Some formatting information is lost, e.g., bold, specific font & size, data masks, etc. Was there a reason you implemented the fill this way instead of changing the text value of the widget?

Is there a way to preserve the other formatting information?

Thank you in advance.

**Comment by chinapandaman** [comment]
Hello,

I'm glad you liked the library. As far as your questions go I will try my best to break them down.

The reason behind the way I implemented the fill method was a design decision I made way back in the days after considering the following:

1. Changing text values of widgets will mostly work for filling one PDF form. However doing so can lead to potential encoding problems when writing the file stream out to a disk file, especially when merging multiple filled PDF forms is a very common use case. Think about say one PDF form has a text field named "foo" and is filled with ten different data sets. But when merging them together the outcome would be one PDF with ten different text fields, all named "foo", that all of them will have the text that the first widget of the ten holds.
2. To avoid the above kind of issues, the PDF form that gets filled by the library will have to be flattened anyway. However after a PDF form gets flattened, the text within each text field are very often not highlightable, which is not something I like.
3. I could never get radio button groups to work by modifying the original widgets.
4. There are many PDF form prep tools out there and the kind of widget attributes each of them generates are not exactly the same. Despite the chaos of that, it is still possible to follow certain patterns to extract and read certain attributes and information of a widget. But that's not the case when it comes to modify these attributes and information as it can very often lead to inconsistent outputs (e.g. simply modifying the attribute that holds the text for a text widget can output PDFs where the text will only show up if the text widget is being "clicked"). This is ultimately the reason that I decided to only extract and read information from widgets, and create new objects based on what I extracted, to keep a consistent output format.

As far as certain formatting information is lost goes, it is also a case by case thing:
1. The library only supports auto-detecting of the [14 standard fonts](https://docs.oracle.com/cd/E96927_01/TSG/FAQ/What%20are%20the%2014%20base%20fonts%20distributed%20with%20Acroba.html). If you are trying to use other fonts with this library, you can register their TrueType files and manually specifying them, whether globally or for each widget. This is documented [here](https://chinapandaman.github.io/PyPDFForm/style/#change-font).
2. Bold and italic are both part of the font properties that come with a font file you register. For [example](https://github.com/chinapandaman/PyPDFForm/tree/master/font_samples) LiberationSerif has a TrueType file for bold, italic, both, and neither.
3. Font size and font color should be auto-detected by the library. If that's not the case please post your template and snippet and I will take a look at why. Regardless the case, they can also be set manually during runtime, documented [here](https://chinapandaman.github.io/PyPDFForm/style/#change-font-size).
4. Underline and data masks are currently not supported. As a matter of fact I didn't even realize these are properties that can be given to widgets during form prep. These might be future action items I will be working on.

I hope I have covered everything. Let me know if you have more questions.

**Comment by mrvisiol** [comment]
Thank you for the quick reply. Given the challenges you encountered, I understand your choices. For my current project I can use your library as-is.

In case this is something you would want to address, here is my specific situation: I have been using the Windows program [Soda PDF](https://www.sodapdf.com/) to make my PDF forms. It does not offer the bold/oblique/italic font names you mentioned. Instead it has buttons to select bold and italic.

<img width="335" alt="image" src="https://github.com/chinapandaman/PyPDFForm/assets/91701091/c3a39716-2c45-4e4c-9a74-5301a56221d7">


I have attached a sample file with various font sizes, colors, background and border styles, before and after using your library to fill the fields. The form fields should match the text above after the fill. The font size seems off (possibly using the text field height rather than the font size?) and the other properties do not persist.

![image](https://github.com/chinapandaman/PyPDFForm/assets/91701091/d838f429-3010-45c8-ba60-231487b43911)
![image](https://github.com/chinapandaman/PyPDFForm/assets/91701091/031251d8-a760-4158-ac08-87bf75299edd)

```python
from PyPDFForm import PdfWrapper

pdf = PdfWrapper("fonttest.pdf")
output = "filled-out.pdf"

fields = pdf.schema["properties"]

fillvalues = {
    "Text1": "Helvetica 8",
    "Text2": "Helvetica 12",
    "Text3": "Helvetica 24",
    "Text4": "Helvetica 8",
    "Text5": "Helvetica 12",
    "Text6": "Helvetica 24",
    "Text7": "Helvetica 8",
    "Text8": "Helvetica 12",
    "Text9": "Helvetica 24",
}

with open(output, "wb+") as output_stream:
    output_stream.write(pdf.fill(fillvalues).read())
```

[fonttest.pdf](https://github.com/chinapandaman/PyPDFForm/files/14032862/fonttest.pdf)
[filled-out.pdf](https://github.com/chinapandaman/PyPDFForm/files/14032864/filled-out.pdf)

If I can be of any help to you, please let me know.

**Comment by chinapandaman** [comment]
Hello, I have some updates for you.

I just made another bump today and with v1.4.5 auto detecting font size and font color should be working as intended now with your template. See [this test case](https://github.com/chinapandaman/PyPDFForm/blob/master/tests/scenario/test_tools.py#L67) and [this output file](https://github.com/chinapandaman/PyPDFForm/blob/master/pdf_samples/scenario/tools/soda_expected.pdf).

The reason it didn't work for your template before was that Soda PDF seems to be adding some tail-string to the text appearance identifiers of its widgets. All I had to change was instead of an equal check, using `startswith` to locate these identifiers and we are able to auto detect them. See [this PR](https://github.com/chinapandaman/PyPDFForm/pull/462).

Now let's talk about font for a bit. So you mentioned that instead of selecting bold/italic font names you have buttons to enable bold/italic. And this is normal for most form prep tools and what's happening under the hood is that by enabling bold/italic, you are really selecting a sub font name of say `Helvetica-Bold` or `Helvetica-Italic` from the `Helvetica` font family, similar to how the [LiberationSerif](https://github.com/chinapandaman/PyPDFForm/tree/master/font_samples) font family also has four different sub font names for bold/italic.

The real problem with font though is that for your template, you enabled bold/italic for `Helvetica`, but they are not present in the text appearance attribute `/DA` for any of the 9 widgets. As long as they are presented in some kind of form I could find a way to auto detect them, see [this test case](https://github.com/chinapandaman/PyPDFForm/blob/master/tests/test_functional.py#L455) and [this output file](https://github.com/chinapandaman/PyPDFForm/blob/master/pdf_samples/test_fill_complex_fonts.pdf). But they are just not there.

I also tried to open your template using one of the tool I use a lot, [DocFly](https://www.docfly.com/dashboard). And although these widgets do have `Helvetica` as font, none of them have bold or italic enabled when viewing in DocFly:

![image](https://github.com/chinapandaman/PyPDFForm/assets/9894243/0ab74c08-c72f-4074-943f-4a1ac6bd5379)

So all and all I'd say there's something weird going on with the way Soda PDF sets font and because of that the library cannot detect font, bold, or italic.

Finally, I don't want to impede your work. So if you are looking for a Python library that does fill a PDF form by changing the value of widgets as if it's done manually, the best one I know is [PyMuPDF](https://github.com/pymupdf/PyMuPDF). The only thing I will say about this one though is that it runs two licenses with a strong copyleft AGPL license for open source uses and a commercial license for non-open source uses. So I would be careful when it comes to licenses.

Let me know if you have more questions.

**Comment by mrvisiol** [comment]
Thank you! You have been more than helpful. I ended up setting the font name in code, for both the bold and normal styles. It's working out well enough for my current project.

Also thank you for the reference to DocFly. I'll try running my pdf through there to see if I get better results.

**Comment by mrvisiol** [comment]
DocFly is working out great for me. One other issue I ran into using Soda PDF is that it considers a max_length value of 0 to be unlimited. PyPDFForm fill() truncates the text to zero characters in this situation. I ended up programmatically changing the max_length to None on text widgets before calling the fill and that works out fine.

Overall PyPDFForm is still the most reliable and useful option and is working out great. Here is a list of my "nice to have" features/fixes:

1) ignore max_length of zero
2) preserve background color, borders on form fields
3) recognize format masks for test (currency, date, etc.)
4) recognize format options for checkboxes and radio buttons

Thanks again.
